#!/usr/bin/env bash
set -Eeuo pipefail
METHOD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; PONI_ROOT="${PONI_ROOT:-$(cd "$METHOD_DIR/../.." && pwd)}"
FSTTA_LR_FAST="${FSTTA_LR_FAST:-1e-8}"; FSTTA_LR_SLOW="${FSTTA_LR_SLOW:-1e-5}"; FSTTA_M="${FSTTA_M:-16}"; FSTTA_N="${FSTTA_N:-32}"
FSTTA_USE_SLOW="${FSTTA_USE_SLOW:-true}"; FSTTA_ENTROPY_MODE="${FSTTA_ENTROPY_MODE:-all}"; FSTTA_MIN_ADAPTATION_PIXELS="${FSTTA_MIN_ADAPTATION_PIXELS:-128}"
FSTTA_Q="${FSTTA_Q:-0.1}"; FSTTA_RHO="${FSTTA_RHO:-0.95}"; FSTTA_TAU="${FSTTA_TAU:-0.7}"; FSTTA_A="${FSTTA_A:-0.9}"; FSTTA_B="${FSTTA_B:-1.1}"
FSTTA_OPTIMIZER="${FSTTA_OPTIMIZER:-AdamW}"; FSTTA_BETA1="${FSTTA_BETA1:-0.9}"; FSTTA_BETA2="${FSTTA_BETA2:-0.99}"; FSTTA_WEIGHT_DECAY="${FSTTA_WEIGHT_DECAY:-0.0}"
FSTTA_MAX_GRAD_NORM="${FSTTA_MAX_GRAD_NORM:-1.0}"; FSTTA_FAST_GRAD_MODE="${FSTTA_FAST_GRAD_MODE:-concordant}"; FSTTA_USE_FAST_LR_SCALER="${FSTTA_USE_FAST_LR_SCALER:-true}"
FSTTA_MOMENTUM="${FSTTA_MOMENTUM:-0.9}"; FSTTA_RESET_OPTIMIZER_EACH_EPISODE="${FSTTA_RESET_OPTIMIZER_EACH_EPISODE:-true}"; FSTTA_EIGEN_EPS="${FSTTA_EIGEN_EPS:-1e-6}"
FSTTA_SLOW_OPTIMIZER="${FSTTA_SLOW_OPTIMIZER:-}"; FSTTA_SLOW_MOMENTUM="${FSTTA_SLOW_MOMENTUM:--1}"; FSTTA_RESET_SLOW_OPTIMIZER_EACH_WINDOW="${FSTTA_RESET_SLOW_OPTIMIZER_EACH_WINDOW:-false}"
METHOD_NAME=FSTTA; METHOD_SLUG=fstta; EVAL_SCRIPT="$METHOD_DIR/eval_poni_fstta.py"; DIAGNOSTICS_FLAG=--fstta-diagnostics
DEFAULT_EXPERIMENT_ROOT="$PONI_ROOT/experiments/global_continual/FSTTA"
METHOD_ARGS=(--fstta-lr-fast "$FSTTA_LR_FAST" --fstta-lr-slow "$FSTTA_LR_SLOW" --fstta-m "$FSTTA_M" --fstta-n "$FSTTA_N" --fstta-q "$FSTTA_Q" --fstta-rho "$FSTTA_RHO" --fstta-tau "$FSTTA_TAU" --fstta-a "$FSTTA_A" --fstta-b "$FSTTA_B" --fstta-steps 1 --fstta-episodic false --fstta-use-slow "$FSTTA_USE_SLOW" --fstta-reset-bn-stats false --fstta-norm-scope bn --fstta-norm-prefixes "" --fstta-entropy-mode "$FSTTA_ENTROPY_MODE" --fstta-min-adaptation-pixels "$FSTTA_MIN_ADAPTATION_PIXELS" --fstta-optimizer "$FSTTA_OPTIMIZER" --fstta-momentum "$FSTTA_MOMENTUM" --fstta-beta1 "$FSTTA_BETA1" --fstta-beta2 "$FSTTA_BETA2" --fstta-weight-decay "$FSTTA_WEIGHT_DECAY" --fstta-max-grad-norm "$FSTTA_MAX_GRAD_NORM" --fstta-reset-optimizer-each-episode "$FSTTA_RESET_OPTIMIZER_EACH_EPISODE" --fstta-eigen-eps "$FSTTA_EIGEN_EPS" --fstta-fast-grad-mode "$FSTTA_FAST_GRAD_MODE" --fstta-use-fast-lr-scaler "$FSTTA_USE_FAST_LR_SCALER" --fstta-slow-optimizer "$FSTTA_SLOW_OPTIMIZER" --fstta-slow-momentum "$FSTTA_SLOW_MOMENTUM" --fstta-reset-slow-optimizer-each-window "$FSTTA_RESET_SLOW_OPTIMIZER_EACH_WINDOW")
TTA_ARGS=(--tta "lr_fast=$FSTTA_LR_FAST" --tta "lr_slow=$FSTTA_LR_SLOW" --tta "M=$FSTTA_M" --tta "N=$FSTTA_N" --tta "q=$FSTTA_Q" --tta "rho=$FSTTA_RHO" --tta "tau=$FSTTA_TAU" --tta "a=$FSTTA_A" --tta "b=$FSTTA_B" --tta "use_slow=$FSTTA_USE_SLOW" --tta "norm_scope=bn_all" --tta "entropy_mode=$FSTTA_ENTROPY_MODE" --tta "min_adaptation_pixels=$FSTTA_MIN_ADAPTATION_PIXELS" --tta "optimizer=$FSTTA_OPTIMIZER" --tta "momentum=$FSTTA_MOMENTUM" --tta "beta1=$FSTTA_BETA1" --tta "beta2=$FSTTA_BETA2" --tta "weight_decay=$FSTTA_WEIGHT_DECAY" --tta "max_grad_norm=$FSTTA_MAX_GRAD_NORM" --tta "reset_optimizer_each_episode=$FSTTA_RESET_OPTIMIZER_EACH_EPISODE" --tta "eigen_eps=$FSTTA_EIGEN_EPS" --tta "fast_grad_mode=$FSTTA_FAST_GRAD_MODE" --tta "use_fast_lr_scaler=$FSTTA_USE_FAST_LR_SCALER" --tta "slow_optimizer=$FSTTA_SLOW_OPTIMIZER" --tta "slow_momentum=$FSTTA_SLOW_MOMENTUM" --tta "reset_slow_optimizer_each_window=$FSTTA_RESET_SLOW_OPTIMIZER_EACH_WINDOW")
source "$PONI_ROOT/scripts/global_continual/run_common.sh"
