BASE_TASK_CONFIG_PATH: "configs/tta_avn/single_source/mp3d/semantic_audiogoal_smt_audio.yaml"
TRAINER_NAME: "ddppo"
NUM_PROCESSES: 1
VIDEO_OPTION: []
VISUALIZATION_OPTION: []
TEST_EPISODE_COUNT: 128
EVAL:
  SPLIT: "train"
  USE_CKPT_CONFIG: False
  ACTION_SELECTION: "sample"
TTA:
  METHOD: "source"
  IDEA:
    SOURCE_COLLECTION: True
